// <auto-generated>
//   Generated by `sek generate` from machine 'ModelProgram'.
//   1 test(s) covering 15/15 transitions.
//   Each test replays an explored action sequence against the SUT binding.
//   The binding assembly path is baked in below; override with the SEK_BINDING
//   environment variable. Regenerate with: sek generate ModelProgram
// </auto-generated>
#nullable disable
using System;
using System.IO;
using System.Reflection;
using System.Runtime.Loader;
using Xunit;

namespace EngLoopKit.Loop.Generated
{
    public sealed class ModelProgramTests
    {
        private const string DefaultBinding = "C:\\boards\\brd009\\EngLoopKit\\src\\EngLoopKit.Core\\bin\\Debug\\EngLoopKit.Core.dll";
        private const string BindingNamespace = "EngLoopKit.Core";

        private readonly Sut _sut = new Sut(
            Environment.GetEnvironmentVariable("SEK_BINDING") ?? DefaultBinding, BindingNamespace);

        [Fact]
        public void ModelProgram_Path01()
        {
            _sut.Step("Loop.Seed");
            _sut.Step("Loop.Bridge");
            _sut.Step("Loop.Architect");
            _sut.Step("Loop.RefactorToFinal");
            _sut.Step("Loop.Model");
            _sut.Step("Loop.Explore");
            _sut.Step("Loop.Coverage");
            _sut.Step("Loop.Explore");
            _sut.Step("Loop.Coverage");
            _sut.Step("Loop.Incident");
            _sut.Step("Loop.Incident");
            _sut.Step("Loop.Postmortem");
            _sut.Step("Loop.Repair");
            _sut.Step("Loop.RefactorToFinal");
            _sut.Step("Loop.Model");
            _sut.Step("Loop.Explore");
            _sut.Step("Loop.Coverage");
            _sut.Step("Loop.RefactorScan");
            _sut.Step("Loop.Seed");
            _sut.Step("Loop.Bridge");
            _sut.Step("Loop.Architect");
            _sut.Step("Loop.RefactorToFinal");
            _sut.Step("Loop.Model");
            _sut.Step("Loop.Explore");
            _sut.Step("Loop.Coverage");
        }

        private sealed class Sut
        {
            private readonly Assembly _asm;
            private readonly string _ns;

            public Sut(string path, string ns)
            {
                var full = Path.GetFullPath(path);
                if (!File.Exists(full))
                    throw new FileNotFoundException(
                        "SUT binding assembly not found: " + full +
                        ". Build the adapter or set the SEK_BINDING environment variable.");
                var dir = Path.GetDirectoryName(full);
                AssemblyLoadContext.Default.Resolving += (ctx, name) =>
                {
                    var candidate = Path.Combine(dir, name.Name + ".dll");
                    return File.Exists(candidate) ? ctx.LoadFromAssemblyPath(candidate) : null;
                };
                _asm = AssemblyLoadContext.Default.LoadFromAssemblyPath(full);
                _ns = ns;
            }

            public void Step(string label, params string[] args)
            {
                var dot = label.LastIndexOf('.');
                Assert.True(dot > 0, "malformed action label: " + label);
                var type = _asm.GetType(_ns + "." + label.Substring(0, dot));
                Assert.True(type != null, "no SUT type for action " + label);
                var method = type.GetMethod(label.Substring(dot + 1),
                    BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance);
                Assert.True(method != null, "no SUT method for action " + label);
                var ps = method.GetParameters();
                var call = new object[ps.Length];
                for (var i = 0; i < ps.Length && i < args.Length; i++)
                    call[i] = Coerce(args[i], ps[i].ParameterType);
                var target = method.IsStatic ? null : Activator.CreateInstance(type);
                method.Invoke(target, call);
            }

            // An observation of an `event` action (the SUT raises it). Replaying model-based
            // tests exercises the same transition; a live conformance harness would instead
            // wait for and verify the event. Kept distinct from Step for that semantics.
            public void Observe(string label, params string[] args) => Step(label, args);

            private static object Coerce(string v, Type t)
            {
                if (t == typeof(string)) return v;
                if (t.IsEnum) return Enum.Parse(t, v, true);
                try { return Convert.ChangeType(v, t); } catch { return v; }
            }
        }
    }
}
